apiVersion: v1
kind: Secret
metadata:
  name: iot-with-dapr-apis-device-secrets
  labels:
    app: iot-with-dapr
    component: actors
    area: app-runtime
data:
  applicationInsightsKey: <base-64-encoded-application-insights-key>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-with-dapr-apis-device
  labels:
    app: iot-with-dapr
    component: device-api
    area: app-runtime
spec:
  selector:
    matchLabels:
      app: iot-with-dapr
      component: device-api
      area: app-runtime
  template:
    metadata:
      labels:
        app: iot-with-dapr
        component: device-api
        area: app-runtime
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "device-api"
    spec:
      containers:
      - name: device-api
        image: ghcr.io/tomkerkhove/iot-with-dapr-device-api
        ports:
        - containerPort: 80
        env:
        - name: APPLICATION_INSIGHTS
          valueFrom:
            secretKeyRef:
              name: iot-with-dapr-apis-device-secrets
              key: applicationInsightsKey
---
apiVersion: v1
kind: Service
metadata:
  name: iot-with-dapr-apis-device-service
  labels:
    app: iot-with-dapr
    component: device-api
    area: app-runtime
spec:
  selector:
    app: iot-with-dapr
    component: device-api
    area: app-runtime
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: iot-with-dapr-apis-device-load-balancer
  annotations:
    # Provide a DNS name which will be exposed under <name>.<location>.cloudapp.azure.com
    # Learn more on https://docs.microsoft.com/en-us/azure/aks/static-ip#apply-a-dns-label-to-the-service
    service.beta.kubernetes.io/azure-dns-label-name: iot-with-dapr-actors
  labels:
    app: iot-with-dapr
    component: device-api
    area: app-runtime
spec:
  selector:
    app: iot-with-dapr
    component: device-api
    area: app-runtime
  ports:
    - protocol: TCP
      port: 9876
      targetPort: 80
  type: LoadBalancer
