apiVersion: v1
kind: Secret
metadata:
  name: iot-with-dapr-actors-secrets
  labels:
    app: iot-with-dapr
    component: actors
    area: app-runtime
data:
  applicationInsightsKey: <base-64-encoded-application-insights-key>
  # This is a hack because it should come from Azure Key Vault, just like all secrets actually
  demoDeviceConnectionString: <base-64-encoded-demo-device-auth-key>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-with-dapr-actors
  labels:
    app: iot-with-dapr
    component: actors
    area: app-runtime
spec:
  selector:
    matchLabels:
      app: iot-with-dapr
      component: actors
      area: app-runtime
  template:
    metadata:
      labels:
        app: iot-with-dapr
        component: actors
        area: app-runtime
      annotations:      
        dapr.io/enabled: "true"
        dapr.io/app-id: "actors-runtime"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: actor-runtime
        image: ghcr.io/tomkerkhove/iot-with-dapr-actor-runtime
        env:
        - name: APPLICATION_INSIGHTS
          valueFrom:
            secretKeyRef:
              name: iot-with-dapr-actors-secrets
              key: applicationInsightsKey
        # This is a local override to configure an authentication key for a given device
        # In reality, this should come from Azure Key Vault, but we are using this approach for demo sake
        # This means that, currently, we can only authenticate for device 'demo-device'
        - name: IOTHUB_CONNECTIONSTRING_DEVICE_demo-device
          valueFrom:
            secretKeyRef:
              name: iot-with-dapr-actors-secrets
              key: demoDeviceConnectionString
